ARG FEDORA_BOOTC_BASE_IMAGE=quay.io/fedora/fedora-bootc@sha256:187d480948fe37a4cc55211b8a594adfc4f85a7d17ac1991331bf98272eb8f94
FROM ${FEDORA_BOOTC_BASE_IMAGE}

RUN --mount=type=bind,source=/build-common.sh,target=/run/build-common.sh,z \
    /run/build-common.sh

COPY nimbus /usr/local/bin/nimbus

RUN chmod 0755 /usr/local/bin/nimbus && \
    restorecon -v /usr/local/bin/nimbus >/dev/null 2>&1 || true
