ARG FCOS_BASE_IMAGE=quay.io/fedora/fedora-bootc:42
FROM ${FCOS_BASE_IMAGE}

RUN --mount=type=bind,source=/build-common.sh,target=/run/build-common.sh,z \
    /run/build-common.sh

COPY nimbus /usr/local/bin/nimbus

RUN chmod 0755 /usr/local/bin/nimbus
