ARG FEDORA_BOOTC_BASE_IMAGE=quay.io/fedora/fedora-bootc@sha256:5f2aa40538a71e32eba8dcdf9059dda10600bac68acef4588cb1aecedcfc6fe2
FROM ${FEDORA_BOOTC_BASE_IMAGE}

RUN --mount=type=bind,source=/build-common.sh,target=/run/build-common.sh,z \
    /run/build-common.sh

COPY nimbus /usr/local/bin/nimbus

RUN chmod 0755 /usr/local/bin/nimbus && \
    restorecon -v /usr/local/bin/nimbus >/dev/null 2>&1 || true
